site_name: dylanisonline
site_description: IT infrastructure lab portfolio
site_author: Dylan Phan
site_url: https://dylanisonline.github.io/

nav:
  - Home: index.md
  - 🌐 Networking:
      - Network Overview: sections/networking/overview.md
      - OpenWRT VM: sections/networking/openwrt-vm.md
      - OpenWRT Config: sections/networking/openwrt-config.md
      - OpenWRT Web GUI: sections/networking/openwrt-gui.md
  - 🖥️ Active Directory:
#      - Overview: sections/active-directory/overview.md
      - Domain Controller Setup: sections/active-directory/dc-setup.md
#      - Forest Configuration: sections/active-directory/ou-design.md
  - 👥 Identity and Access Management:
      - OU Design: sections/iam/iam-ou-design.md
#      - User and Admin Accounts: sections/iam/iam-user-accounts.md
#  - 💻 Workstations:
#      - Workstation Roles: sections/workstations/workstation-roles.md
#      - Workstation GPOs: sections/workstations/workstation-gpos.md
#      - Workstation Onboarding: sections/workstations/workstation-onboarding.md
#  - 📁 File Server:
#      - File Server Deployment: sections/file-server/file-server.md
  - About Me: about.md

theme:
  name: dracula
  custom_dir: overrides

markdown_extensions:
  - attr_list

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - glightbox
