site_name: dylanisonline
site_description: IT infrastructure lab portfolio
site_author: Dylan Phan
site_url: https://dylanisonline.github.io/

nav:
  - Home: index.md
  - 🌐 Networking:
      - Network Overview: sections/networking/overview.md
      - OpenWRT VM: sections/networking/openwrt-vm.md
      - OpenWRT Config: sections/networking/openwrt-config.md
      - OpenWRT Web GUI: sections/networking/openwrt-gui.md
  - 🖥️ Active Directory:
#      - Overview: sections/active-directory/overview.md
      - Domain Controller Setup: sections/active-directory/domain-controller.md
      - Account Creation: sections/active-directory/account-creation.md
      - Joining Computers: sections/active-directory/join-workstations.md
  - 👥 OUs/Groups/GPOs:
      - OUs: sections/groups-and-gpos/ous.md
      - Groups: sections/groups-and-gpos/groups.md
      - GPOs: sections/groups-and-gpos/gpos.md
  - 📁 File Server:
      - File Server Deployment: sections/file-server/file-server.md
  - About Me: about.md

theme:
  name: dracula
  custom_dir: overrides

markdown_extensions:
  - attr_list

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - glightbox
